#Display information on the screen to admins (title/subtitle). Admin must have permission!
screen_information: true

#Sending reports with no any administrator on the server.
send_without_admin: true

#History of messages, this option add features:
# 1) if the administration solves the problem, can mark the report as solved
# 2) history of messages
# 3) receiving messages sent during the absence of the administration on the server, after entering
enable_history: false
database:
  #Avaiable databases: SQLite, MySQL (recommended).
  type: mysql
  table: helpop

  #If you use SQLite, you can set file's name.
  filename: database.db

  #If you use MySQL, you have to set database parameters.
  host: localhost
  port: 3306
  database: helpop
  username: root
  password: ''
  ssl: false