#This is configuration of style of messages
admin_message_format: "&7[&cHelpOP&7] &6<player>&7: &f<message>"

#Message to player after badly use
incorrect_use: "&cYou have to type issue! &7/helpop message"

#Information to player when nobody of administrations is on the server. (only if history of messages is disabled)
no_admins: "&cThere is no administration on the server currently :/."

#Display information on the screen to admins (title/subtitle). Admin must have permission!
screen_information: true
screen_title: "&cNew report from &6<player>&c!"
screen_subtitle: "&f<message>"

#Permissions configuration
permissions:
  reporting: helpop.report
  no_permission_reporting: "&cYou don't have permissions to use this command!"

  receiving: helpop.receive

  screen_receiving: helpop.screen

  check_solved: helpop.check
  messages_history: helpop.history
  no_permission_admin: "&cYou don't have permissions to use this command!"


#History of messages, this option add features:
# 1) if the administration solves the problem, it can mark the report as solved
# 2) history of messages
# 3) receiving messages sent during the absence of the administration on the server, after entering
enable_history: false
database:
  #Avaiable databases: SQLite, MySQL.
  type: sqlite
  table: helpop

  #If you use SQLite, you can set file's name.
  filename: database.db

  #If you use MySQL, you have to set database parameters.
  host: localhost
  port: 3306
  database: helpop
  username: helpop
  password: ''
  ssl: false