name: ${project.name}
version: ${project.version}
main: pl.techbrat.spigot.helpop.HelpOPTB
authors: [TechBrat]
description: ${project.description}
website: ${project.url}
commands:
  helpop:
    description: Main command to use
    usage: /helpop message
    permission: helpoptb.command