name: ${project.name}
version: ${project.version}
main: pl.techbrat.spigot.helpop.HelpOPTB
authors: [TechBrat]
description: ${project.description}
website: ${project.url}
soft depend: [LuckPerms]
commands:
  helpop:
    description: Main command to use
    permission: helpoptb.command
    usage: /helpop <message>
  response:
    description: Response message to player
    permission: helpoptb.response
    usage: /response <player> <message>