name: HelpOPTB
version: '${project.version}'
main: pl.techbrat.spigot.helpop.HelpOPTB
authors: [ TechBrat ]
description: Simple plugin for reporting issues.
website: techbrat.pl
commands:
  helpop:
    description: Main command to use
    usage: /helpop message